name: Lint Action
author: Samuel Meuli
description: GitHub Action for detecting and fixing linting errors

inputs:
  auto_fix:
    description: Whether linters should try to fix code style issues automatically
    required: false
    default: false

  # CSS

  stylelint:
    description: Enable or disable stylelint checks
    required: false
    default: false
  stylelint_extensions:
    description: Extensions of files to check with stylelint
    required: false
    default: "css"
  stylelint_dir:
    description: Directory where the stylelint command should be run
    required: false

  # Go

  gofmt:
    description: Enable or disable gofmt checks
    required: false
    default: false
  gofmt_extensions:
    description: Extensions of files to check with gofmt
    required: false
    default: "go"
  gofmt_dir:
    description: Directory where the gofmt command should be run
    required: false

  # JavaScript

  eslint:
    description: Enable or disable ESLint checks
    required: false
    default: false
  eslint_extensions:
    description: Extensions of files to check with ESLint
    required: false
    default: "js"
  eslint_dir:
    description: Directory where the ESLint command should be run
    required: false

  prettier:
    description: Enable or disable Prettier checks
    required: false
    default: false
  prettier_extensions:
    description: Extensions of files to check with Prettier
    required: false
    default: "js"
  prettier_dir:
    description: Directory where the Prettier command should be run
    required: false

  # Python

  black:
    description: Enable or disable Black checks
    required: false
    default: false
  black_extensions:
    description: Extensions of files to check with Black
    required: false
    default: "py"
  black_dir:
    description: Directory where the Black command should be run
    required: false

  flake8:
    description: Enable or disable Flake8 checks
    required: false
    default: false
  flake8_extensions:
    description: Extensions of files to check with Flake8
    required: false
    default: "py"
  flake8_dir:
    description: Directory where the Flake8 command should be run
    required: false

  # Swift

  swiftlint:
    description: Enable or disable SwiftLint checks
    required: false
    default: false
  swiftlint_extensions:
    description: Extensions of files to check with SwiftLint
    required: false
    default: "swift"
  swiftlint_dir:
    description: Directory where the SwiftLint command should be run
    required: false

runs:
  using: node12
  main: ./src/index.js

branding:
  icon: check
  color: green
